[environment]
substeps = 3                            # iterations of collision logic ran per step
grid_scale_factor = 1.5                 # gridcell size multiplier, decrease for large gridcells
max_particles_per_grid_cell = 8         # max particles per gridcell
friction = 0.95                         # friction multiplier. 1 = no friction, 0 = no movement

[experiment]
domain_size = 8500                      # length (in micrometers) of one side of the square simulation space
initial_mode = "single"                 # options: single (1 cell), full (entire space filled with cells)
initial_wound = "none"                  # creates an initial wound in a full tissue. options: none, circle, triangle, square
wound_width = 5200                      # wound width / diameter / altitude (in micrometers)
end_step = -1                           # ends the simulation at this specified time step (-1 = unending)

[data_collection]
capture_data = false                    # capture and save permanent experiment data?
data_path = ""                          # path to folder where all experiment data will be stored
max_image_pixel_cells = 10              # maximum number of fibroblasts in a pixel in image capture mode before the pixel turns white
save_video = false                      # save video of imaging data?
video_frame_rate = 8                    # frame rate in the video capture (fps)

[cells]
max_cell_count = 100000                 # max cell capacity
cell_radius = 17                        # fibroblast radius (in micrometers)
cell_cycle_duration = 60                # duration of the cell cycle (in steps)
cell_repulsion = 0.005                  # how agressively cells repulse. larger = more aggressive
reproduction_offset = 1.5               # distance from the parent that the daughter is created
max_cell_speed = 0.004                  # max cell speed (micrometers / step)
cell_turn_speed = 0.01                  # cell turning speed (in radians / step)
cell_turn_chance = 0.5                  # chance per step to change turning state (0-1)

[inhibition]
inhibition_radius = 1.99                # distance in which cells detect neighbors (in cell radii)
inhibition_threshold = 1                # arbitrary point at which cells enter g0
inhibition_exit_threshold = 0.2         # how low inhibition must fall to exit g0
inhibition_factor = 0.05                # inhibition counter increment

[ecm]
max_ecm_count = 50000                   # max ecm capacity
min_ecm_period = 20                     # shortest allowed time between ecm deposits
ecm_detection_radius = 20               # distance cells detect ecm (in cell radii)
ecm_threshold = 7                       # number of ecm at which cells cease ecm deposition
ecm_avoidance_strength = 0.000001       # magnitude of ecm avoidance vector (in micrometers)

[display]
cell_radius_scalar = 1.0                # visual size multiplier for visibility at large scales
phase_colors = [                        # color palette for cell phases
    0x858585,
    0x66ccff,
    0xffcc66,
    0x66ff66,
    0xff6699
]
draw_ecm_lines = false                  # draw connecting lines between ecm particles?