[environment]
substeps = 5                            # iterations of collision logic ran per tick
grid_scale_factor = 1.5                 # gridcell size multiplier, decrease for large gridcells
max_particles_per_grid_cell = 8         # max particles per gridcell
friction = 0.95                         # friction multiplier. 1 = no friction, 0 = no movement

[experiment]
initial_mode = "single"                 # options: single (1 cell), full (entire space filled with cells)
initial_wound = "none"                  # creates an initial wound in a full tissue. options: none, circle, triangle, square
end_step = -1                           # ends the simulation at this specified time step (-1 = unending)
capture_data = false                    # capture and save permanent experiment data?
data_path = ""                          # path to folder where all experiment data will be stored
max_image_pixel_cells = 10              # maximum number of fibroblasts in a pixel in image capture mode before the pixel turns white

[cells]
max_cell_count = 100000                 # max cell capacity
cell_radius = 0.002                     # scale of simulation. smaller = larger scale
cell_cycle_duration = 60                # duration of the cell cycle (in ticks)
cell_repulsion = 0.005                  # how agressively cells repulse. larger = more aggressive
reproduction_offset = 1.5               # distance from the parent that the daughter is created
max_cell_speed = 0.004                  # max cell speed (in cell radii / tick)

[inhibition]
inhibition_radius = 1.99                # distance in which cells detect neighbors (in cell radii)
inhibition_threshold = 1                # arbitrary point at which cells enter g0
inhibition_exit_threshold = 0.2         # how low inhibition must fall to exit g0
inhibition_factor = 0.05                # inhibition counter increment

[ecm]
max_ecm_count = 50000                   # max ecm capacity
min_ecm_period = 20                     # shortest allowed time between ecm deposits
ecm_detection_radius = 20               # distance cells detect ecm (in cell radii)
ecm_threshold = 7                       # number of ecm at which cells cease ecm deposition
ecm_avoidance_strength = 0.000001       # magnitude of ecm avoidance vector

[display]
cell_radius_scalar = 1.0                # visual size multiplier for visibility at large scales
phase_colors = [                        # color palette for cell phases
    0x858585,
    0x66ccff,
    0xffcc66,
    0x66ff66,
    0xff6699
]

[tools]
scalpel_radius = 0.10                   # scalpel tool radius
